with_asp.net/Models/ErrorViewModel.cs
namespace IANM_web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

with_asp.net/Controllers/q1Controller.cs
using IANM_web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace IANM_web.Controllers
{
    public class q1Controller : Controller
    {
        private readonly ILogger<q1Controller> _logger;

        public q1Controller(ILogger<q1Controller> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Profil()
        {
            return View();
        }

        public IActionResult Perusahaan()
        {
            return View();
        }

        public IActionResult Layanan()
        {
            return View();
        }

        public IActionResult Team()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

with_asp.net/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IANM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IANM_web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header class="border-bottom box-shadow fixed-top bg-light cont-head">
        <div class="container">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light">
                <div class="container">
                    <div >
                        <a asp-area="" asp-page="/Index"><img class="nav-logo" src="~/img/IANMNet.svg"/></a>
                    </div>
                    <div class="nav-right">
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item px-2">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="q1" asp-action="Index">Beranda</a>
                                </li>
                                <li class="nav-item px-2">
                                    <a class="nav-link text-dark" asp-area=""  asp-controller="q1" asp-action="Profil">Profil</a>
                                </li>
                                <li class="nav-item px-2">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="q1" asp-action="Perusahaan">Perusahaan</a>
                                </li>
                                <li class="nav-item px-2">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="q1" asp-action="Layanan">Layanan</a>
                                </li>
                                <li class="nav-item px-2">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="q1" asp-action="Team">Team</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
        </div> 
    </header>
    <main role="main" class="">
            @RenderBody()
    </main>

    <footer class="border-top footer text-muted">
        <div class="container">
            <p>Copyright &copy; IANM Indonesia 2018 - 2022</p>
            <a asp-area="" asp-page="/Index"><img class="footer-logo" src="img/IANMNet.svg"/></a>
            
               
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

with_asp.net/Views/q1/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="top-wrapper">
    <div class="container">
        <div class="top-text">
            <h1>IANM NET</h1>
            <p>Solusi internet <strong>berkualitas</strong> dengan harga terjangkau <br/>untuk seluruh wilayah <strong>Indonesia.</strong></p>
        </div>
    </div>
</div>
<div class="about-wrapper">
    <div class="container">
        <div class="head">
            <h4 class="-shadow-sm">
                Tentang kami
            </h4>
        </div>
        <div class="cont-text">
            <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
                It has survived not only five centuries, but also the leap into electronic typesetting, 
                remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset 
                sheets containing Lorem Ipsum passages, and more recently with desktop publishing software 
                like Aldus PageMaker including versions of Lorem Ipsum.
            </p>
        </div>
    </div>
</div>
<div class="primacy-wrapper">
    <div class="container">
        <div class="primacy">
            <div class="primacy-item">
                <h5 class="primary-head">Jaringan kami hadir di seluruh <strong>INDONESIA</strong>, akses internet <strong>SUPER CEPAT</strong> untuk kebutuhan download, browsing, dan gaming kamu.</h5>
            </div>
            <div class="primacy-item">
                <img src="/img/speed.svg">
            </div>
            <div class="primacy-item">
                <img src="~/img/server-amico.svg">
            </div>
            <div class="primacy-item">
                <h5 class="primary-head">Dukungan <strong>24 Jam</strong>  penuh dari tim <strong>PROFESIONAL</strong>, untuk menjamin anda dalam berselancar internet.</h5>
            </div>
        </div>
    </div>
</div>
<div class="btm-wrapper border-top box-shadow">
    <div class="container">
        <div class="btm">
            <div class="btm-list">
                <div class="btm-item">
                    <div class="contact">
                        
                        <h6 class="btm-head">Kontak kami</h6>
                        <i class="fa-solid fa-map-location"></i>
                        <p>Keputih Perintis IV no 5B, Surabaya</p>
                        <i class="fa-solid fa-square-phone"></i>
                        <p>+62953-9878-0271</p>
                        <i class="fa-solid fa-envelope"></i>
                        <p>ianm@gmail.com</p>
                    </div>                 
                </div>
                <div class="btm-item">
                    <div class="menu">
                        <h6 class="btm-head">Menu</h6>
                        <ul>
                            <li>
                                Profile
                            </li>
                            <li>
                                Perusahaan
                            </li>
                            <li>
                                Layanan
                            </li>
                            <li>
                                Team
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="btm-item">
                    <div class="sosmed">
                        <h6 class="btm-head">Media sosial</h6>
                        <div class="sosmed-list">
                            <div class="sosmed-icon">
                                <i class="fa-brands fa-linkedin"></i>
                            </div class="sosmed-icon">
                            <div class="sosmed-icon">
                                <i class="fa-brands fa-instagram-square"></i>
                            </div>
                            <div class="sosmed-icon">
                                <i class="fa-brands fa-twitter-square"></i>
                            </div>
                            <div class="sosmed-icon">
                                <i class="fa-brands fa-facebook-square"></i>
                            </div>
                            
                            
                        </div>   
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

with_asp.net/Views/q1/layanan.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Layanan";
}

<div class="service-wrapper">
    <div class="container">
        <div class="cont-card">
            <h3> Kami Menyediakan paket layanan berikut </h3>
            <div class="row row-cols-1 row-cols-md-3 g-4">
              <div class="col">
                <div class="card h-100">
                  <img class="icon-paket" src="~/img/speed-icon.svg" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">Bronze</h5>
                    <ul class="list-none">
                        <li><strong>Up to 10 Mbps</strong></li>
                        <li>Kuota unlimited tanpa FUP</li>
                        <li>Dukungan 24/7 full</li>
                        <li><strong>RP 175.000;</strong></li>
                    </ul>
                  </div>
                  <div class="card-footer">
                    <small class="text-muted">Hubungi kami ></small>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card h-100" style="list-style-type: none;">
                  <img class="icon-paket" src="~/img/speed-icon.svg" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">Silver</h5>
                    <ul class="list-none">
                        <li><strong>Up to 30 Mbps</strong></li>
                        <li>Kuota unlimited tanpa FUP</li>
                        <li>Dukungan 24/7 full</li>
                        <li><strong>RP 275.000;</strong></li>
                    </ul>
                  </div>
                  <div class="card-footer">
                    <small class="text-muted">Hubungi kami ></small>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card h-100">
                  <img class="icon-paket" src="~/img/speed-icon.svg" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">Gold</h5>
                    <ul class="list-none">
                        <li><strong>Up to 50 Mbps</strong></li>
                        <li>Kuota unlimited tanpa FUP</li>
                        <li>Dukungan 24/7 full</li>
                        <li><strong>RP 375.000;</strong></li>
                    </ul>
                  </div>
                  <div class="card-footer">
                    <small class="text-muted">Hubungi kami ></small>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>

with_asp.net/Views/q1/perusahaan.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Prusahaan";
}
<div class="primacy-wrapper perusahaan">
    <div class="container">
        <div class="primacy">
            <div class="primacy-item">
                <h4 class="text-company"><strong>VISI</strong></h4>
                <h6 class="text-company">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</h6>

                <h4 class="text-company pt-5"><strong>MISI</strong></h4>
                <h6 class="text-company">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. <br />
                    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s <br />
                    when an unknown printer took a galley of type and scrambled it to make a type specimen book <br />
                    but also the leap into electronic typesetting, remaining essentially unchanged. 
                </h6>

            </div>
            <div class="primacy-item" style="text-align: center;">
                <img src="/img/company.svg">
            </div>
        </div>
    </div>
</div>

with_asp.net/Views/q1/profil.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Profil";
}

<div class="profil-wrapper">
    <div class="container">
        <div class="foto-list">
            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
              </div>
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img style="width: 100%" src="~/img/slide2.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                  <img src="~/img/slide3.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                  <img src="~/img/slide1.png" class="d-block w-100" alt="...">
                </div>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>        
        </div>
        <div class="text-profil border-bottom box-shadow">
                <h4 class="text-company">IANM Net</h4>
                <p class="text-company">Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
                    It has survived not only five centuries, but also the leap into electronic typesetting, 
                    remaining essentially unchanged. It was popularised in the 1960s with the release of 
                    Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing 
                    software like Aldus PageMaker including versions of Lorem Ipsum</p>
        </div>
        <div class="text-profil border-bottom box-shadow">
            <h4 class="text-company">Sejarah</h4>
            <p class="text-company">Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
                    It has survived not only five centuries, but also the leap into electronic typesetting, 
                    remaining essentially unchanged. It was popularised in the 1960s with the release of 
                    Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing 
                    software like Aldus PageMaker including versions of Lorem Ipsum</p>
        </div>
        <div class="text-profil border-bottom box-shadow">
             <h4 class="text-company">Pengembangan</h4>
             <p class="text-company">Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
                    It has survived not only five centuries, but also the leap into electronic typesetting, 
                    remaining essentially unchanged. It was popularised in the 1960s with the release of 
                    Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing 
                    software like Aldus PageMaker including versions of Lorem Ipsum</p>
         </div>
    </div>
</div>

with_asp.net/Views/q1/team.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Team";
}

<div class="service-wrapper">
    <div class="container">
        <div class="cont-card">
            <h3> Team Kami </h3>
            <div class="tim-list">
                <div class="tim-item">
                    <div class="card tim-card shadow-sm" style="width: 24rem;">
                      <h5 class="card-title pt-3">OWNER</h5>
                      <img src="~/img/icon-people.png" class="card-img-top tim-img" alt="...">
                      <div class="card-body">
                        <h5 class="card-title ">Ifanu Antoni</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                      </div>
                      <div class="card-body">
                        <a href="#" class="card-link">Card link</a>
                        <a href="#" class="card-link">Another link</a>
                      </div>
                    </div>
                </div>
                <div class="tim-item">
                    <div class="card tim-card shadow-sm" style="width: 24rem;">
                      <h5 class="card-title pt-3">CTO</h5>
                      <img src="~/img/icon-people.png" class="card-img-top tim-img" alt="...">
                      <div class="card-body">
                        <h5 class="card-title">Nama Lengkap</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                      </div>
                      <div class="card-body">
                        <a href="#" class="card-link">Card link</a>
                        <a href="#" class="card-link">Another link</a>
                      </div>
                    </div>
                </div>
                <div class="tim-item">
                    <div class="card tim-card shadow-sm" style="width: 24rem;">
                      <h5 class="card-title pt-3">STAFF</h5>
                      <img src="~/img/icon-people.png" class="card-img-top tim-img" alt="...">
                      <div class="card-body">
                        <h5 class="card-title">Nama Lengkap</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                      </div>
                      <div class="card-body">
                        <a href="#" class="card-link">Card link</a>
                        <a href="#" class="card-link">Another link</a>
                      </div>
                    </div>
                </div>
                <div class="tim-item">
                    <div class="card tim-card shadow-sm" style="width: 24rem;">
                      <h5 class="card-title pt-3">STAFF</h5>
                      <img src="~/img/icon-people.png" class="card-img-top tim-img" alt="...">
                      <div class="card-body">
                        <h5 class="card-title">Nama Lengkap</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                      </div>
                      <div class="card-body">
                        <a href="#" class="card-link">Card link</a>
                        <a href="#" class="card-link">Another link</a>
                      </div>
                    </div>
            </div>
        </div>
    </div>
</div>